version: '3'
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:4200"
    volumes:
      - ./src:/app/src
      - ./angular.json:/app/angular.json
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
